solarsystem:
    celestial_bodies:
        stars:            
            -   name: "Sun"

        planets:
            -   name: "Earth"
                orbit_radius: 4

            -   name: "Jupiter"          
                orbit_radius: 9

            -   name: "Mars"
                orbit_radius: 6

        natural_satellites:
            -   name: "Moon"
                planet_adjacent: "Earth"

            -   name: "Europa"
                planet_adjacent: "Jupiter"
          
            -   name: "Phobos"
                planet_adjacent: "Mars"
          

    rate: 15
      
           