solarsystem:
    celestial_bodies:

      -   name: "Sun"
          label: "Star"
          label_id: 1
      
      -   name: "Earth"
          label: "Planet"
          label_id: 2
          orbit_radius: 2
    
      -   name: "Moon"
          label: "Natural Satellite"
          label_id: 3
          

      -   name: "Jupiter"
          label: "Planet"
          label_id: 2
          orbit_radius: 5

      -   name: "Europa"
          label: "Natural Satellite"
          label_id: 3
      
      -   name: "Mars"
          label: "Planet"
          label_id: 2
          orbit_radius: 3

      -   name: "Phobos"
          label: "Natural Satellite"
          label_id: 3

    rate: 15
      
           