version: '3'
services: 

  ps:
    container_name: ps_container
    image: a205390f3bf9
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
    network_mode: host
    stdin_open: true
    tty: true
