version: '3'
services: 

  ps:
    container_name: ps_container
    image: d8a
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
      - ./../:/root/PS
    network_mode: host
    stdin_open: true
    tty: true
